package add_refuerzoVI;
// Generated 30-may-2017 15:16:59 by Hibernate Tools 4.3.1



/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellidos;
     private String fechaAlta;
     private String dni;
     private String fechaIngreso;

    public Pacientes() {
    }

	
    public Pacientes(int id, String nombre, String apellidos, String dni) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.dni = dni;
    }
    public Pacientes(int id, String nombre, String apellidos, String fechaAlta, String dni, String fechaIngreso) {
       this.id = id;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaAlta = fechaAlta;
       this.dni = dni;
       this.fechaIngreso = fechaIngreso;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(String fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


